### ISSUE TITLE
Port code to Cabal 1.25.x

### ISSUE THREAD

**Issue by mpickering** [peti/jailbreak-cabal#12]
When trying to compile with `HEAD` there are quite a few errors like..

```
Main.hs:25:37: error:
    Not in scope: type constructor or class ‘Dependency’
   |
25 |     relaxLibraryTree :: CondTree v [Dependency] Library -> CondTree v [Dependency] Library
   |                                     ^^^^^^^^^^
```

I think the API of `Cabal` must have slightly changed.

**Comment by peti** [comment]
Yes, the `Dependency` type has been re-factored quite a bit. Fixing this will need some investigation, I suppose, especially considering that Cabal 1.25 is in a rather experimental state and may undergo further changes.

**Comment by mpickering** [comment]
I wondered in the `*-configuration` file that the version of `Cabal` is fixed to be the same as the boot compiler. It would perhaps be simpler for now to build the right version of the `Cabal` library so people can use `ghcHEAD` with jailbreaking?

**Comment by mpickering** [comment]
When will this change propagate to `nixpkgs`?

**Comment by peti** [comment]
Within a day or two.
