### ISSUE TITLE
jailbreak-cabal incorrectly reproduces the `tested-with` directive

### ISSUE THREAD

**Issue by ixmatus** [peti/jailbreak-cabal#16]
I didn't see an issue for this already so I thought I'd report it. Note that we're using `nixpkgs-17.09@74286ec9e76be7cd00c4247b9acb430c4bd9f1ce`.

The field in the cabal file before jailbreaking:

```
tested-with: ghc
```

... and after jailbreaking:

```
tested-with: OtherCompiler "ghc" -any
```

**Comment by peti** [comment]
This is a bug in older version of `Cabal`. Recent versions pretty-print those values correctly, i.e. the issue no longer exists in the `nixos-18.03` release branch (nor does it exist in `master`). Do these mis-printed valued cause any actual errors? Or can we just ignore them?

**Comment by ixmatus** [comment]
The mis-printed field value does cause an error for us but it was trivially resolved by adding a `prePatch` step that stripped the field from the cabal file before jail breaking. I will close this since it is no longer an issue in nixpkgs (>=) 18.03.
