### ISSUE TITLE
Weird output when using with Cabal 1.22.x to process arithmoi 

### ISSUE THREAD

**Issue by peti** [peti/jailbreak-cabal#3]
The arithmoi Cabal file says:

    library
        build-depends       : base >= 4 && < 5, array >= 0.3 && < 0.6, ghc-prim,
                              integer-gmp, containers >= 0.3 && < 0.6, random >= 1.0 && < 1.1,
                              mtl >= 2.0 && < 2.3

jailbreak-cabal transforms this to:

    library
        build-depends:
            base -any,
            array -any,
            ghc-prim -any,
            integer-gmp -any,
            containers -any,
            random -any,
            mtl -any

        ...

        build-depends:
            base >=4 && <5,
            array >=0.3 && <0.6,
            ghc-prim -any,
            integer-gmp -any,
            containers >=0.3 && <0.6,
            random >=1.0 && <1.1,
            mtl >=2.0 && <2.3

Strangely enough, this issue seems to occur only with Cabal 1.22.x. In version 1.20.x we didn't have that problem.

**Comment by shlevy** [comment]
This seems to be blocking jailbreaking for `haskell-ng.packages.ghcHEAD`

**Comment by shlevy** [comment]
(working on a workaround where the `jailbreak-cabal` binary used for HEAD builds comes from 7.8.4)

**Comment by peti** [comment]
Oh, I had the same idea. :-) I'll commit in a second if you don't beat me to it.

**Comment by shlevy** [comment]
I got caught up in making `makeOverridable` work for functions so that I could call override on `mkDerivation`, you'll probably win :grinning:

**Comment by peti** [comment]
Reported in https://github.com/haskell/cabal/issues/2343.
