### ISSUE TITLE
Doesn't jailbreak ReadArgs properly

### ISSUE THREAD

**Issue by joelteon** [peti/jailbreak-cabal#5]
Trying to jailbreak ReadArgs (see https://hackage.haskell.org/package/ReadArgs-1.2.2/ReadArgs.cabal) yields this:

```
(lots of stuff)

library
    exposed-modules:
        ReadArgs
    build-depends:
        base -any,
        system-filepath -any,
        text -any

executable ReadArgsEx
    main-is: ReadArgsEx.hs
    build-depends:
        base >=4.3.1.0 && <5,
        system-filepath >=0.4.7 && <0.5,
        text >=0.11.1.13 && <12

test-suite ReadArgsSpec
    type: exitcode-stdio-1.0
    main-is: ReadArgsSpec.hs
    build-depends:
        hspec >=1.3 && <2.1,
        base >=4.3.1.0 && <5,
        system-filepath >=0.4.7 && <0.5,
        text >=0.11.1.13 && <12
```

**Comment by peti** [comment]
I cannot reproduce that result. I get the following output:

    library
        build-depends: base -any, system-filepath -any, text -any
        exposed-modules: ReadArgs
        exposed: True
        buildable: True

    executable ReadArgsEx
        build-depends: base -any, system-filepath -any, text -any
        main-is: ReadArgsEx.hs
        buildable: True

    test-suite ReadArgsSpec
        build-depends: hspec -any, base -any, system-filepath -any,
                       text -any
        type: exitcode-stdio-1.0
        main-is: ReadArgsSpec.hs
        buildable: True

Which version of Cabal did you use to build the `jailbreak` binary?
    build-depends: hspec -any, base -any, system-filepath -any,
                   text -any
    type: exitcode-stdio-1.0
    main-is: ReadArgsSpec.hs
    buildable: True

**Comment by joelteon** [comment]
Sorry, forgot to mention that this is with GHC 7.10.1 from HaskellNG, which I think uses Cabal 1.22?

**Comment by peti** [comment]
Yeah, Cabal 1.22.x gives me the same result. Not sure what's going on ... I'll need to investigate this. Thanks for the report.

**Comment by joelteon** [comment]
@peti it seems that the build info metadata has been moved into the `targetBuildDepends` fields in the `BuildInfo` of the `Executable`, `TestSuite`, and `Benchmark` datatypes.

Can write a fix but it'll take a bit of busywork.

**Comment by joelteon** [comment]
Ignore my previous comment, jailbreak-cabal already does that...

**Comment by joelteon** [comment]
Oh, no it doesn't. You've defined `relaxExeTree` and `relaxTestTree`, but never actually use them.

**Comment by peti** [comment]
http://hackage.haskell.org/package/jailbreak-cabal-1.3 contains the fix.
