### ISSUE TITLE
Cabal omits true branch in conditional

### ISSUE THREAD

**Issue by cstrahan** [peti/jailbreak-cabal#9]
Pandoc's cabal file gets mangled by jailbreak-cabal; this:

    Executable make-pandoc-man-pages
      Main-Is:       make-pandoc-man-pages.hs
      Hs-Source-Dirs: man
      Build-Depends: pandoc,
                     base >= 4.2 && < 5,
                     directory >= 1 && < 1.3,
                     filepath >= 1.1 && < 1.4,
                     old-time >= 1.0 && < 1.2,
                     time >= 1.2 && < 1.6
      Default-Language: Haskell98
      if flag(make-pandoc-man-pages)
        Buildable:   True
      else
        Buildable:   False

is turned into this:

    executable make-pandoc-man-pages
    
        if flag(make-pandoc-man-pages)
        else
            buildable: False
        main-is: make-pandoc-man-pages.hs
        build-depends:
            pandoc -any,
            base -any,
            directory -any,
            filepath -any,
            old-time -any,
            time -any
        default-language: Haskell98
        hs-source-dirs: man

Note: this is using jailbreak-cabal compiled with GHC 7.10.

(for reference: http://hackage.haskell.org/package/pandoc-1.13.2/revision/2.cabal)

**Comment by abbradar** [comment]
This also breaks `cheapskate` build, which is needed for `Idris`.

**Comment by abbradar** [comment]
https://github.com/haskell/cabal/issues/2598

**Comment by cstrahan** [comment]
@abbradar Thank you for submitting the issue upstream.

**Comment by peti** [comment]
Interestingly enough, the problem doesn't seem to occur when building `jailbreak-cabal` with Cabal 1.18.x.

**Comment by abbradar** [comment]
One possible workaround for now can be using `jailbreak-cabal` from `packages.ghc784`; would it be hard/too hacky?

**Comment by peti** [comment]
It's possible. It would just trigger a lot of re-builds, I suppose, so it's kind-of expensive.

**Comment by abbradar** [comment]
Yeah, already noticed that. I have come with a rather hacky solution instead: https://github.com/abbradar/nixpkgs/commit/c877e29dcfa4f34db1aeda4f5840100a90f302ae . Do we want this ugly thing mainlined or rather wait till the proper fix? OTOH this allows us to build affected packages.

**Comment by abbradar** [comment]
NM, I looked at how `pandoc` problem is avoided and think I'll just use `sed` too.

**Comment by peti** [comment]
I pushed https://github.com/peti/nixpkgs/commit/daeefd2834c372456bcbf83ebf3a282f0720f83a to have test builds run at http://hydra.cryp.to/jobset/nixpkgs/haskell-updates.

**Comment by peti** [comment]
I've edited the `jailbreak-cabal` page on Hackage to constrain the `Cabal` version to 1.18.x: http://hackage.haskell.org/package/jailbreak-cabal-1.3/revisions/.

**Comment by peti** [comment]
Well, the version built with Cabal 1.18.x causes build failures, too: <http://hydra.cryp.to/eval/457274#tabs-still-fail>. The `refcount` package illustrates the issue: <http://hydra.cryp.to/build/870257/log/raw>. I'm not yet sure what's going on there, but those packages built correctly when we were using jailbreak-cabal with Cabal 1.22.x.

**Comment by abbradar** [comment]
Ouch! Does using Cabal 1.20.x fix this? If not, I can investigate?

**Comment by peti** [comment]
OK, building `jailbreak-cabal` with Cabal 1.20.x gives us the best performance for the time being. I'll merge the updates to `master` in a minute.

**Comment by peti** [comment]
Contrary to what commit https://github.com/haskell/cabal/commit/e6bff69dfc5f4cc715e32ca60c9fa0c057195e07 says, this issue does *not* appear to be fixed in `Cabal 1.22.4.0`. When I build `jailbreak-cabal` with GHC 7.10.2, then it breaks the `pandoc.cabal` file just like old versions used to.
